min_sensor_dist: .01
self_see_default_padding: .08
self_see_default_scale: 1.0
self_see_links:
- name: pelvis
- name: l_leg_hip_yaw
- name: l_leg_hip_roll
- name: l_leg_thigh
- name: l_leg_shank
- name: l_leg_ankle_roll
- name: l_foot
- name: r_leg_hip_yaw
- name: r_leg_hip_roll
- name: r_leg_thigh
- name: r_leg_shank
- name: r_leg_ankle_roll
- name: r_foot
- name: utorso
- name: neck_link
- name: head_link
- name: l_arm_shoulder_pitch
- name: l_arm_shoulder_roll
- name: l_arm_shoulder_yaw
- name: l_arm_elbow
- name: l_arm_wrist_yaw
- name: l_arm_wrist_roll
- name: l_arm_wrist_yaw2
- name: r_arm_shoulder_pitch
- name: r_arm_shoulder_roll
- name: r_arm_shoulder_yaw
- name: r_arm_elbow
- name: r_arm_wrist_yaw
- name: r_arm_wrist_roll
- name: r_arm_wrist_yaw2

#- name: waist
#- name: waist_lidar_mount_link
#- name: waist_hokuyo_laser_frame
#- name: l_hand
#- name: r_hand




